files: ^(Backend/Core/app|Backend/Core/tests)\/.+\.py$

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-docstring-first

-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.1
    hooks:
    -   id: add-trailing-comma
        args: [--py36-plus]

-   repo: https://github.com/asottile/pyupgrade
    rev: v3.3.2
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]

-   repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [
            "--remove-all-unused-imports",
            "--remove-unused-variables",
            "--ignore-init-module-imports",
            "--remove-all-unused-imports"
        ]

-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: [--line-length=93]

-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.1'
    hooks:
    -   id: bandit
        args: ["--exclude", "tests"]

-   repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        args: [
            '--ignore=F401',
            '--max-line-length=93'
        ]

-   repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
    -   id: isort
        args: [ --profile=black ]
