set $cors '';

# Match anything not empty
if ($http_origin ~ '.+') {
    set $cors 'origin_matched';
}

# Preflight requests
if ($request_method = OPTIONS) {
    set $cors '${cors} & preflight';
}

# standard CORS request
if ($cors = 'origin_matched') {
    # for standard CORS requests only those headers are required
    add_header Access-Control-Allow-Origin $http_origin always;
    add_header Access-Control-Allow-Credentials 'true' always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
    add_header 'Access-Control-Expose-Headers' 'Set-Cookie' always;

}

# preflight CORS request
if ($cors = 'origin_matched & preflight') {
    # standard CORS headers are required
    add_header Access-Control-Allow-Origin $http_origin always;
    add_header Access-Control-Allow-Credentials 'true' always;

    # additional headers are required and need to match exactly what was sent in CORS request
    add_header Access-Control-Allow-Methods $http_access_control_request_method always;
    add_header Access-Control-Allow-Headers $http_access_control_request_headers always;
    add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, PATCH, OPTIONS' always;
    add_header 'Access-Control-Allow-Headers' 'Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Requested-With' always;
    add_header 'Access-Control-Expose-Headers' 'Set-Cookie' always;
    add_header 'Access-Control-Max-Age' 1728000;
    add_header 'Content-Type' 'text/plain charset=UTF-8';
    add_header 'Content-Length' 0;
    return 204;
}